FROM node:22-alpine AS builder
RUN corepack enable
WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
RUN yarn install --immutable

COPY tsconfig.json ./
COPY prisma/ prisma/
COPY src/ingestion/ src/ingestion/

RUN npx prisma generate
RUN tsc

FROM node:22-alpine
WORKDIR /app

COPY --from=builder /app/dist/ingestion ./dist
COPY --from=builder /app/node_modules ./node_modules

CMD ["node", "dist/index.js"]
